### ISSUE TITLE
Google Play: java.lang.NullPointerException

### ISSUE THREAD

**Issue by thisandagain** [mozilla/webmaker-core#358]
Our crash stats on Google Play are quite good (only one) but we should try to track this down:

``` bash
Last reported: Jul 14, 6:56 PM
Reports this week: 1
Reports total: 2
Application version: 1.0
Android version: Android 4.4
Device:
- VF685 (VF685)
- WALTON
```

``` bash
java.lang.NullPointerException
at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1422)
at android.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:479)
at android.app.FragmentManagerImpl.popBackStackImmediate(FragmentManager.java:494)
at android.app.Activity.onBackPressed(Activity.java:2248)
at org.mozilla.webmaker.BaseActivity.goBack(BaseActivity.java:10)
at org.mozilla.webmaker.javascript.WebAppInterface$1.run(WebAppInterface.java:170)
at android.os.Handler.handleCallback(Handler.java:808)
at android.os.Handler.dispatchMessage(Handler.java:103)
at android.os.Looper.loop(Looper.java:193)
at android.app.ActivityThread.main(ActivityThread.java:5299)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:825)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:641)
at dalvik.system.NativeStart.main(Native Method)
```

``` bash
Jul 12, 1:52 PM
1.0
Galaxy Grand Prime (fortuna3g)
while i was typing it crashed

Jul 7, 1:02 PM
1.0
Xperia M (C1904)
unable to change the font size

Jun 21, 6:48 PM
1.0
WALTON
not working correctly
```

**Comment by thisandagain** [comment]
Possibly related (compat library bug when dismissing the keyboard): 
http://stackoverflow.com/questions/10456077/nullpointerexception-in-fragmentmanager

**Comment by ryanwarsaw** [comment]
@thisandagain I feel that fixing this should be pretty straight forward and would like to tackle this tomorrow.

**Comment by thisandagain** [comment]
@ryanw-se Great! Thanks! :smile:

**Comment by ryanwarsaw** [comment]
After further research, I wasn't able to replicate the problem and the logs don't give me enough information to properly diagnose the issue.

**Comment by Pomax** [comment]
closing as unverifiable. metrics will have to tell us whether this is still a problem
