### ISSUE TITLE
Android crash report: play store

### ISSUE THREAD

**Issue by k88hudson** [mozilla/webmaker-core#619]
This seems to be popping up every so often since 1.2.0 (very unfrequently):

```
java.lang.NullPointerException: Attempt to read from field 'android.os.Handler android.app.Activity.mHandler' on a null object reference
at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1427)
at android.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:483)
at android.app.FragmentManagerImpl.popBackStackImmediate(FragmentManager.java:498)
at android.app.Activity.onBackPressed(Activity.java:2479)
at org.mozilla.webmaker.BaseActivity.goBack(BaseActivity.java:10)
at org.mozilla.webmaker.web.javascript.WebAppInterface$1.run(WebAppInterface.java:203)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:211)
at android.app.ActivityThread.main(ActivityThread.java:5317)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1016)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
```

**Comment by ryanwarsaw** [comment]
Going to add this to the list of tickets to evaluate with the new router implementation, since one of the steps to implementing it will be to clean up the things we are holding in memory and this appears to be a null reference to one of those objects.
