### ISSUE TITLE
Spike in crashes last week

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker-core#644]
Between Sept 2 and Sept 6 there were 110 crashes on version 1.2 and 197 crashes on version 1.3.

212 of those crashes were reported as `RuntimeException (@WebmakerWebView:<init>:22) {main}`

This is the trace from google play:

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.mozilla.webmaker/org.mozilla.webmaker.activity.Login}: java.lang.RuntimeException: java.lang.RuntimeException: Use SharedXWalkView if you want to support shared mode
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2356)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2418)
at android.app.ActivityThread.access$900(ActivityThread.java:154)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5295)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Use SharedXWalkView if you want to support shared mode
at org.xwalk.core.ReflectionHelper.handleException(ReflectionHelper.java:233)
at org.xwalk.core.ReflectionHelper.handleException(ReflectionHelper.java:237)
at org.xwalk.core.ReflectionHelper.init(ReflectionHelper.java:132)
at org.xwalk.core.ReflectionHelper.loadClass(ReflectionHelper.java:199)
at org.xwalk.core.ReflectionHelper$ConstructorHelper.loadConstructor(ReflectionHelper.java:37)
at org.xwalk.core.ReflectionHelper.createInstance(ReflectionHelper.java:246)
at org.xwalk.core.XWalkView.<init>(XWalkView.java:192)
at org.mozilla.webmaker.view.WebmakerWebView.<init>(WebmakerWebView.java:22)
at org.mozilla.webmaker.WebmakerActivity.onStart(WebmakerActivity.java:95)
at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1236)
at android.app.Activity.performStart(Activity.java:6006)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2319)
... 10 more
Caused by: java.lang.RuntimeException: Use SharedXWalkView if you want to support shared mode
... 21 more
```

To me, the important part there is `Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Use SharedXWalkView if you want to support shared mode`.

And, 92 of those crashes were reported as `NullPointerException (@BaseActivity:goBack:10) {main}`

This is the trace from google play:

```
java.lang.NullPointerException
at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1410)
at android.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:474)
at android.app.FragmentManagerImpl.popBackStackImmediate(FragmentManager.java:489)
at android.app.Activity.onBackPressed(Activity.java:2185)
at org.mozilla.webmaker.BaseActivity.goBack(BaseActivity.java:10)
at org.mozilla.webmaker.web.javascript.WebAppInterface$1.run(WebAppInterface.java:203)
at android.os.Handler.handleCallback(Handler.java:800)
at android.os.Handler.dispatchMessage(Handler.java:100)
at android.os.Looper.loop(Looper.java:194)
at android.app.ActivityThread.main(ActivityThread.java:5409)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:525)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:606)
at dalvik.system.NativeStart.main(Native Method)
```

@Pomax had an interesting idea: waking the app between version refreshes would certainly break.

Can we wrap our `goBack` to see?

cc @Pomax @ryanw-se

**Comment by xmatthewx** [comment]
spike was temporary
